### ISSUE TITLE
App install error

### ISSUE THREAD

**Issue by cmdada** [termux/termux-gui#41]
Installing on a pixel 3a with termux and the termux:styling plugin results in the error "App not installed as package conflicts with an existing package

**Comment by tareksander** [comment]
You likely installed Termux from f-droid, you can't mix install sources for (most) Termux plugins. Since there is currently no release of Termux:GUI on f-droid, you have to install Termux and the other plugins from GitHub Actions builds: https://github.com/termux/termux-gui/issues/2#issuecomment-981069771
