### ISSUE TITLE
Can't install on tinno u304ac

### ISSUE THREAD

**Issue by konn-neko** [termux/termux-gui#7]
![Screenshot_20211229-004632.png](https://user-images.githubusercontent.com/92604391/147634974-b8ea379d-a322-4128-a0cf-3046dba6d109.png)

The same goes for the one uploaded on f-droid

**Comment by tareksander** [comment]
Like described on the [Termux readme](https://github.com/termux/termux-app#Installation) you can't mix installation sources like Github releases and f-droid. You probably have Termux from f-droid, so the Github release doesn't work. You would first have to uninstall Termux and then reinstall it from Github. The f-droid version currently doesn't work because of signing key issues you can see [this thread](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10240) for progress on that.

**Comment by Sohil876** [comment]
> Like described on the [Termux readme](https://github.com/termux/termux-app#Installation) you can't mix installation sources like Github releases and f-droid. You probably have Termux from f-droid, so the Github release doesn't work. You would first have to uninstall Termux and then reinstall it from Github. The f-droid version currently doesn't work because of signing key issues you can see [this thread](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10240) for progress on that.

My termux and termux api are from fdroid and im trying to install termux gui from fdroid, still install fails.

**Comment by tareksander** [comment]
> > Like described on the [Termux readme](https://github.com/termux/termux-app#Installation) you can't mix installation sources like Github releases and f-droid. You probably have Termux from f-droid, so the Github release doesn't work. You would first have to uninstall Termux and then reinstall it from Github. The f-droid version currently doesn't work because of signing key issues you can see [this thread](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10240) for progress on that.
> 
> My termux and termux api are from fdroid and im trying to install termux gui from fdroid, still install fails.

See #4
